### PR TITLE
Add WasiTest.java

### PR DESCRIPTION
**Pull request by Superice666**

### CODE REVIEW

**Comment by Superice666** [comment]
DO NOT Merge! 
@kawamuray As you can see, WasiConfig.PreopenDir doesn't work on windows, it throws a `Access is denied. (os error 5)` expection . Even if I use absolute path, I still get the expection. Could you please help me solve the problem? Thx a lot.

**Comment by kawamuray** [comment]
Hmm, I have no idea what's wrong with it at the moment. Unfortunately it's difficult for me to dig into this as I don't have a local windows environment to test with.
Assuming the error is coming from wasmtime runtime, would it be possibly an issue of wasmtime itself? Can you try running tiny snippet that does the same thing with (probably new version of) wasmtime in Rust and see if you see the same error?

**Comment by Superice666** [comment]
@kawamuray It seems that this problem doesn't happen on wasmtime`0.28.0` while we are still using `0.19.0`.
I tried to update wasmtime for wasmtime-java, but I found that the api of wasmtime were redesigned. I'm not familiar with rust and wasmtime so I can't replace the old code with new API. Could you please do that, thanks a lot!

**Comment by kawamuray** [comment]
Cool, good to hear that. Yeah updating wasmtime dep involves certain some redesign as some APIs has been updated with backward incompatible changes. I'll try to find time to work on that.

**Comment by kawamuray** [comment]
@Superice666 I've work upgrading wasmtime dep at #17 and made a release 0.6.0 with it. Can you try with the latest release?

**Comment by Superice666** [comment]
@kawamuray It works well! Thanks a lot!

**Pull request closed without merging**
